spring:
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                highlight_sql: true
        defer-datasource-initialization: true

    sql:
        init:
            mode: always

    data:
        web:
            pageable:
                one-indexed-parameters: true
        redis:
            host: localhost
            port: 6379

    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        username: ENC(bGvDWXdgAsFNCvvwrW9+eQ==)
        password: ENC(yb9c5bnqFBYAoXvuBddv6A==)
        url: ENC(VDulTKVcDKlyXOvmiK5/diPARDSH31SjTdWYIFrdcRrKKCExvC2x5jPireljXeSYkULO1V5zzEW+/0RrGu8tJlrRo9ZxvcXlIyrGMCttEZKYy501NI12s23HuzL3xCyU0uZzFFicleA=)

    mvc:
        path match:
            matching-strategy: ant_path_matcher

    security:
        oauth2:
          client:
              provider:
                kakao:
                    authorization-uri: https://kauth.kakao.com/oauth/authorize
                    token-uri: https://kauth.kakao.com/oauth/token
                    user-info-uri: https://kapi.kakao.com/v2/user/me
                    user-name-attribute: id
              registration:
                kakao:
                    client-id: ??? API ?
                    client-secret: ??? Secret ?
                    client-authentication-method: client_secret_post
                    redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                    authorization-grant-type: authorization_code
                    client-name: kakao
                    scope:
                        - profile_nickname
jasypt:
    key: ${JASYPT_KEY}

jwt:
    token:
        secret: jwt??